### ISSUE TITLE
Need Updated pip package.

### ISSUE THREAD

**Issue by amolkahat** [ansible/pytest-ansible#22]
We need updated pip package.

**Comment by amolkahat** [comment]
When I run pytest with ansible 2.7
```
[root@0c5c52d8ae30 pki-pytest-ansible]# pytest --ansible-host-pattern master --ansible-inventory host test_hello.py -qsvvv
Traceback (most recent call last):
  File "/usr/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/_pytest/config/__init__.py", line 49, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python2.7/site-packages/_pytest/config/__init__.py", line 186, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/usr/lib/python2.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/lib/python2.7/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python2.7/site-packages/_pytest/config/__init__.py", line 656, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python2.7/site-packages/_pytest/config/__init__.py", line 828, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python2.7/site-packages/_pytest/config/__init__.py", line 780, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 267, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 291, in load_module
    six.exec_(co, mod.__dict__)
  File "/usr/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pytest_ansible/plugin.py", line 21, in <module>
    from ansible.vars import VariableManager
ImportError: cannot import name VariableManager
```

After this issue, I clone Repo, then installed it.
Then it run successfully. 
```
[root@0c5c52d8ae30 tmp]# git clone https://github.com/ansible/pytest-ansible.git
Cloning into 'pytest-ansible'...
remote: Enumerating objects: 1209, done.
remote: Total 1209 (delta 0), reused 0 (delta 0), pack-reused 1209
Receiving objects: 100% (1209/1209), 244.58 KiB | 333.00 KiB/s, done.
Resolving deltas: 100% (791/791), done.
[root@0c5c52d8ae30 tmp]# cd pytest-ansible/
[root@0c5c52d8ae30 pytest-ansible]# pip install . 
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Processing /tmp/pytest-ansible
Requirement already satisfied: ansible in /usr/lib/python2.7/site-packages (from pytest-ansible==2.0.1)
Requirement already satisfied: pytest in /usr/lib/python2.7/site-packages (from pytest-ansible==2.0.1)
Requirement already satisfied: jinja2 in /usr/lib64/python2.7/site-packages (from ansible->pytest-ansible==2.0.1)
Requirement already satisfied: PyYAML in /usr/lib64/python2.7/site-packages (from ansible->pytest-ansible==2.0.1)
Requirement already satisfied: paramiko in /usr/lib/python2.7/site-packages (from ansible->pytest-ansible==2.0.1)
Requirement already satisfied: cryptography in /usr/lib64/python2.7/site-packages (from ansible->pytest-ansible==2.0.1)
Requirement already satisfied: setuptools in /usr/lib/python2.7/site-packages (from ansible->pytest-ansible==2.0.1)
Requirement already satisfied: atomicwrites>=1.0 in /usr/lib/python2.7/site-packages (from pytest->pytest-ansible==2.0.1)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/lib/python2.7/site-packages (from pytest->pytest-ansible==2.0.1)
Requirement already satisfied: pluggy>=0.7 in /usr/lib/python2.7/site-packages (from pytest->pytest-ansible==2.0.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/lib/python2.7/site-packages (from pytest->pytest-ansible==2.0.1)
Requirement already satisfied: pathlib2>=2.2.0; python_version < "3.6" in /usr/lib/python2.7/site-packages (from pytest->pytest-ansible==2.0.1)
Requirement already satisfied: py>=1.5.0 in /usr/lib/python2.7/site-packages (from pytest->pytest-ansible==2.0.1)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python2.7/site-packages (from pytest->pytest-ansible==2.0.1)
Requirement already satisfied: funcsigs; python_version < "3.0" in /usr/lib/python2.7/site-packages (from pytest->pytest-ansible==2.0.1)
Requirement already satisfied: MarkupSafe in /usr/lib64/python2.7/site-packages (from jinja2->ansible->pytest-ansible==2.0.1)
Requirement already satisfied: pynacl>=1.0.1 in /usr/lib64/python2.7/site-packages (from paramiko->ansible->pytest-ansible==2.0.1)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python2.7/site-packages (from paramiko->ansible->pytest-ansible==2.0.1)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/lib64/python2.7/site-packages (from paramiko->ansible->pytest-ansible==2.0.1)
Requirement already satisfied: idna>=2.1 in /usr/lib/python2.7/site-packages (from cryptography->ansible->pytest-ansible==2.0.1)
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/lib64/python2.7/site-packages (from cryptography->ansible->pytest-ansible==2.0.1)
Requirement already satisfied: enum34; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography->ansible->pytest-ansible==2.0.1)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python2.7/site-packages (from cryptography->ansible->pytest-ansible==2.0.1)
Requirement already satisfied: ipaddress; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography->ansible->pytest-ansible==2.0.1)
Requirement already satisfied: scandir; python_version < "3.5" in /usr/lib64/python2.7/site-packages (from pathlib2>=2.2.0; python_version < "3.6"->pytest->pytest-ansible==2.0.1)
Requirement already satisfied: pycparser in /usr/lib/python2.7/site-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography->ansible->pytest-ansible==2.0.1)
Installing collected packages: pytest-ansible
  Found existing installation: pytest-ansible 1.3.1
    Uninstalling pytest-ansible-1.3.1:
      Successfully uninstalled pytest-ansible-1.3.1
  Running setup.py install for pytest-ansible ... done
Successfully installed pytest-ansible-2.0.1
[root@0c5c52d8ae30 pytest-ansible]# cd -
/tmp
[root@0c5c52d8ae30 tmp]# cd /root/pki-pytest-ansible/
[root@0c5c52d8ae30 pki-pytest-ansible]# pytest --ansible-host-pattern master --ansible-inventory host test_hello.py -qsvvv
=============================================================================================== test session starts ===============================================================================================
platform linux2 -- Python 2.7.15, pytest-3.9.2, py-1.7.0, pluggy-0.8.0 -- /usr/bin/python2
cachedir: .pytest_cache
ansible: 2.7.0
rootdir: /root/pki-pytest-ansible, inifile: pytest.ini
plugins: logger-0.3.0, autochecklog-0.2.0, ansible-2.0.1, ansible-playbook-0.3.0
collected 2 items                                                                    
```

**Comment by jlaska** [comment]
Please retest using pytest-ansible-2.0.2.  If the problem remains, please reopen this issue.  Thanks!
