### ISSUE TITLE
Error in retrieve host_pattern attribute

### ISSUE THREAD

**Issue by CFSNM** [ansible/pytest-ansible#57]
These two integration tests from tower-qa repository are failing when upgrading from Tower 4.0.0 to Tower 4.0.1. This error is caused to the mismatch between the inventory groups (4.0.0 -> tower, 4.0.1 -> automationcontroller):

- tests.api.job_templates.test_job_template_callbacks.TestJobTemplateCallbacks.test_provision_with_provided_variables_needed_to_start
- tests.api.job_templates.test_job_template_callbacks.TestJobTemplateCallbacks.test_provision_job_template_with_limit[regular_tower_instance]

The root cause is here:

## Error Message
failed on setup with "AttributeError: type HostManager has no attribute 'tower[0]'"
## Trace
Traceback (most recent call last):
  File "/home/ec2-user/venvs/venv/lib64/python3.8/site-packages/pytest_ansible/fixtures.py", line 20, in ansible_module
    return getattr(host_mgr, host_mgr.options['host_pattern'])
  File "/home/ec2-user/venvs/venv/lib64/python3.8/site-packages/pytest_ansible/host_manager/__init__.py", line 68, in __getattr__
    raise AttributeError("type HostManager has no attribute '%s'" % attr)
AttributeError: type HostManager has no attribute 'tower[0]'

We will need to change the code to, depending of the tower version, search for tower[0] or automationcontroller[0] attribute

**Comment by CFSNM** [comment]
FYI @kdelee @Zokormazo

**Comment by CFSNM** [comment]
Closing as it is not necessary to modify this repository
